spring:
#  h2:
#    console:
#      path: /h2-console/semantic
#      # enabled web
#      enabled: true
#    demo:
#      enabled: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:semantic;DATABASE_TO_UPPER=false
#    username: root
#    password: semantic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supersonic?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: local
    password: local

server:
  port: 9080

authentication:
  enable: true
  exclude:
    path: /api/auth/user/register,/api/auth/user/login
  token:
    http:
      header:
        key: Authorization

time:
  threshold: 100

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml


llm:
  parser:
    url:  http://127.0.0.1:9092
embedding:
  url: http://127.0.0.1:9092
functionCall:
  url: http://127.0.0.1:9092

# cw llm模型解析配置
cw:
  parser:
    url:  http://127.0.0.1:9092
    queryToDslPath: /queryToDsl
    vecSimilaritySearchPath: /vec_similarity_search
    dimValSimilaritySearchPath: /dim_val_similarity_search
    funSimilaritySearchPath: /func_similarity_search
